name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: IDF Dependencies
      run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
    - name: Git Pull ESP-IDF
      run: mkdir -p ~/esp && cd ~/esp && git clone --recursive https://github.com/espressif/esp-idf.git
    - name: ./Install IDF
      run: cd ~/esp/esp-idf && ./install.sh esp32
    - name: . $HOME/esp/esp-idf/export.sh
      run: . $HOME/esp/esp-idf/export.sh
    - name: cd ../../
      run: cd ../../
    - name: cd micropython/ports/esp32
      run: cd micropython/ports/esp32 && make USER_C_MODULES=../../../../Modules/micropython.cmake


